apiVersion: v1
kind: Service
metadata:
  name: adguard-home-service
  namespace: adguard-home
spec:
  selector:
    app: adguard-home
  externalIPs:
    - "192.168.0.156"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: admin
    - protocol: UDP
      port: 53
      targetPort: 53
      name: dns
    - protocol: TCP
      port: 53
      targetPort: 53
      name: dns-tcp
  type: ClusterIP