apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pvzge-ingress
  namespace: pvzge
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.ioio/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: pvzge-app.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pvzge
                port:
                  number: 80