ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Replace with your cert-manager ClusterIssuer
  hosts:
    - host: gitea.internal
      paths:
        - path: /
    - host: gitea.mostrelyable.com
      paths:
        - path: /
  tls:
    - secretName: gitea-mostrelyable-com-tls
      hosts:
        - gitea.mostrelyable.com
    - secretName: gitea-internal-tls
      hosts:
        - gitea.internal

gitea:
  config:
    server:
      ROOT_URL: "https://gitea.mostrelyable.com"
    actions:
      ENABLED: true

# Using the bundled PostgreSQL HA chart.
# It is strongly recommended to set your own passwords.
# You can do this by creating a secret with the passwords and referencing it here,
# or by setting the passwords directly in this file.
# For example:
# postgresql-ha:
#   postgresql:
#     password: "your-gitea-password"
#     postgresPassword: "your-postgres-password"
#     repmgrPassword: "your-repmgr-password"
#   pgpool:
#     adminPassword: "your-pgpool-admin-password"
postgresql-ha:
  enabled: true