apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meme-storage-ingress
  namespace: bots
  annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: websecure 
      traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
      - memes.mostreliable.bid
  rules:
    - host: memes.mostreliable.bid
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meme-storage-service
                port:
                  number: 80