apiVersion: v1
kind: Service
metadata:
  name: meme-storage-service
  namespace: bots
spec:
  selector:
    app: meme-storage-bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      