apiVersion: batch/v1
kind: CronJob
metadata:
  name: reddit-bot
  labels:
    app: reddit-bot
spec:
  schedule: "*/30 * * * *"  # runs every 30 minutes
  concurrencyPolicy: Forbid  # avoid overlapping runs
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: reddit-bot
          annotations:
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/role: "reddit-bot-role"
            vault.hashicorp.com/agent-inject-secret-botsecrets: "kv/reddit-bot/secrets"
            vault.hashicorp.com/agent-inject-template-botsecrets: |
              {{- with secret "kv/reddit-bot/secrets" -}}
              export TELEGRAM_REDDIT_BOT_TOKEN="{{ .Data.data.tg_reddit_bot_token }}"
              export TELEGRAM_REDDIT_BOT_CHAT_ID="{{ .Data.data.tg_reddit_bot_chat_id }}"
              export SUBREDDIT_LIST="{{ .Data.data.subreddit_list }}"
              {{- end }}
        spec:
          securityContext:
            fsGroup: 1000
            runAsUser: 1000
            runAsGroup: 1000
          serviceAccountName: reddit-bot-sa
          restartPolicy: OnFailure
          containers:
            - name: reddit-bot
              image: dima032398485/reddit_bot:latest
              imagePullPolicy: Always
              command: ["/bin/sh", "-c"]
              args:
                - |
                  . /vault/secrets/botsecrets && python main.py
              lifecycle:
                preStop:
                  exec:
                    command: ["/bin/sh", "-c", "sleep 1"]
              resources:
                requests:
                  cpu: "100m"
                  memory: "128Mi"
                limits:
                  cpu: "250m"
                  memory: "256Mi"
              volumeMounts:
                - name: reddit-bot-data
                  mountPath: /data
          volumes:
            - name: reddit-bot-data
              persistentVolumeClaim:
                claimName: reddit-bot-data