apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich
  namespace: immich
  labels:
    app: immich-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-app
  template:
    metadata:
      labels:
        app: immich-app
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "immich-role"
        vault.hashicorp.com/agent-inject-secret-db.env: "immich/data/postgres"
        vault.hashicorp.com/agent-inject-template-db.env: |
          {{- with secret "immich/data/postgres" -}}
          export DB_USERNAME='{{ .Data.data.postgres_user }}'
          export DB_PASSWORD='{{ .Data.data.postgres_password }}'
          export DB_NAME='{{ .Data.data.postgres_db }}'
          {{- end }}
    spec:
      serviceAccountName: immich-sa
      initContainers:
        - name: wait-for-postgres
          image: postgres:14
          command:
            - sh
            - -c
            - |
              until pg_isready -h immich-psql-service -p 5432; do
                echo "Waiting for postgres..."
                sleep 2
              done
      containers:
        - name: immich
          image: ghcr.io/immich-app/immich-server:v2.4.1
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", ". /vault/secrets/db.env && exec node /usr/src/app/server/dist/main.js"]
          ports:
            - containerPort: 2283
              name: http
            - containerPort: 3003
              name: immich-ml
          env:
            - name: IMMICH_MEDIA_LOCATION
              value: /mnt/data/immich
            - name: UPLOAD_LOCATION
              value: /mnt/data/immich
            - name: MACHINE_LEARNING_URL
              value: immich-ml-service
            - name: DB_HOSTNAME
              value: immich-psql-service
            - name: REDIS_HOSTNAME
              value: immich-redis-service
          readinessProbe:
            httpGet:
              path: /
              port: 2283
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /auth/login
              port: 2283
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              memory: "2Gi"
              cpu: "2000m"
            limits:
              memory: "4Gi"
              cpu: "4000m"
          volumeMounts:
            - name: immich-lybrary-pv
              mountPath: /mnt/data/immich
      volumes:
        - name: immich-lybrary-pv
          persistentVolumeClaim:
            claimName: immich-lybrary-pvc