apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-pv-hostpath
  labels:
    app: immich
    volume-type: hostpath-immich-library
spec:
  storageClassName: "" # Important for static binding; must match PVC if PVC specifies it
  capacity:
    storage: 300Gi # Ensure this is sufficient and matches your physical disk size
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # IMPORTANT: Retain data even if PVC is deleted
  hostPath:
    path: "/mnt/data/immich"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3s-lab # Ensure this matches the hostname of your k3s node
