apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-ml
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-ml-app
  template:
    metadata:
      labels:
        app: immich-ml-app
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "immich-role"
        vault.hashicorp.com/agent-inject-secret-db.env: "kv/immich/secrets"
        vault.hashicorp.com/agent-inject-template-db.env: |
          {{- with secret "kv/immich/secrets" -}}
          export DB_USERNAME='{{ .Data.data.postgres_user }}'
          export DB_PASSWORD='{{ .Data.data.postgres_password }}'
          export DB_NAME='{{ .Data.data.postgres_db }}'
          {{- end }}
    spec:
      serviceAccountName: immich-sa
      containers:
        - name: immich-ml
          image: ghcr.io/immich-app/immich-machine-learning:v2.4.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
              name: immich-ml
          env:
            - name: TRANSFORMERS_CACHE
              value: /cache
            - name: DB_HOSTNAME
              value: immich-psql-service
            - name: REDIS_HOSTNAME
              value: immich-redis-service
          readinessProbe:
            httpGet:
              path: /ping
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: 3003
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: ml-cache
              mountPath: /cache
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
      volumes:
        - name: ml-cache
          emptyDir: {}