apiVersion: v1
kind: Service
metadata:
  name: immich-psql-service
  namespace: immich
spec:
  clusterIP: None
  selector:
    app: immich-psql
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres