apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-psql-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "" # Explicitly set to empty string for static provisioning
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: immich-psql
      volume-type: hostpath-immich-psql
