apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-psql-pv-hostpath
  labels:
    app: immich-psql
    volume-type: hostpath-immich-psql
spec:
  storageClassName: "" # Important for static binding
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # IMPORTANT: Retain data even if PVC is deleted
  hostPath:
    path: "/mnt/data/immich-postgres"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3s-lab # Ensure this matches the hostname of your k3s node
