apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-cf-headers
  namespace: immich
spec:
  headers:
    customRequestHeaders:
      CF-Access-Client-Id: ""
      CF-Access-Client-Secret: ""
